/** Banco de perguntas original DISC v1. Cada linha: [D, I, S, C]. Revisar com profissional de RH/psicologia antes de uso comercial. */
export const DISC_V1_GROUPS: ReadonlyArray<readonly [string, string, string, string]> = [
  ['Decidido', 'Entusiasmado', 'Paciente', 'Detalhista'],
  ['Competitivo', 'Sociável', 'Leal', 'Preciso'],
  ['Direto', 'Persuasivo', 'Calmo', 'Analítico'],
  ['Ousado', 'Expressivo', 'Acolhedor', 'Cuidadoso'],
  ['Determinado', 'Otimista', 'Constante', 'Organizado'],
  ['Corajoso', 'Comunicativo', 'Tolerante', 'Criterioso'],
  ['Independente', 'Animado', 'Cooperativo', 'Metódico'],
  ['Firme', 'Carismático', 'Gentil', 'Sistemático'],
  ['Assertivo', 'Espontâneo', 'Previsível', 'Rigoroso'],
  ['Exigente', 'Brincalhão', 'Receptivo', 'Perfeccionista'],
  ['Enérgico', 'Inspirador', 'Ponderado', 'Lógico'],
  ['Autoconfiante', 'Extrovertido', 'Confiável', 'Disciplinado'],
  ['Pioneiro', 'Divertido', 'Apoiador', 'Observador'],
  ['Resoluto', 'Popular', 'Harmonioso', 'Reservado'],
  ['Objetivo', 'Envolvente', 'Persistente', 'Prudente'],
  ['Forte', 'Amigável', 'Estável', 'Exato'],
  ['Ambicioso', 'Motivador', 'Compreensivo', 'Focado em regras'],
  ['Desafiador', 'Falante', 'Humilde', 'Questionador'],
  ['Impulsivo', 'Descontraído', 'Calmo sob pressão', 'Cauteloso'],
  ['Líder', 'Influenciador', 'Mediador', 'Planejador'],
  ['Rápido', 'Alegre', 'Prestativo', 'Minucioso'],
  ['Controlador', 'Convincente', 'Moderado', 'Racional'],
  ['Empreendedor', 'Aberto', 'Dedicado', 'Estruturado'],
  ['Competente', 'Cativante', 'Sereno', 'Consciencioso'],
];
